maps/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'all_maps/$', 'maps.views.home', name='index_maps'),
    url(r'show/(?P<pk>\d+)/$', 'maps.views.show', name='show_map'),
    url(r'search/$', 'maps.views.search', name='search_maps'),
    url(r'view_maptype/(?P<pk>\d+)/$', 'maps.views.view_maptype', name="view_maptype"),
]

patterns/urls.py
from django.conf.urls import url
from patterns import views

urlpatterns = [
    url(r'list_pattern_types/$', views.list_pattern_types, name="list_pattern_types"),
    url(r'view_pattern_type/(?P<pk>\d+)/$', views.view_pattern_type, name="view_pattern_type"),

    url(r'list_pattern_type_stages/(?P<pk>\d+)/$', views.list_pattern_type_stages, name="list_pattern_type_stages"),
    url('search/$', views.search, name='search_patterns'),
    url(r'view_pattern/(?P<pk>\d+)/$', views.view_pattern, name="view_pattern"),
]

realestate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'realties.views.home'),
    url(r'^maps/', include('maps.urls')),
    url(r'^realties/', include('realties.urls')),
    url(r'^others/', include('others.urls')),
    url(r'^patterns/', include('patterns.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patterns/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils import timezone


class PatternType(models.Model):
    name = models.CharField('الأسم', max_length=255)
    description = models.TextField('الوصف')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['id']


class PatternTypeStage(models.Model):
    name = models.CharField('الأسم', max_length=255)
    description = models.TextField('الوصف')
    typee = models.ForeignKey(PatternType, null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name + ' - ' + self.typee.name

    class Meta:
        ordering = ['id']


class PatternFloor(models.Model):
    name = models.CharField('الاسم ', max_length=255)
    # image = models.ImageField('الصوره ', upload_to='media/upload/patternsFloor/', blank=True, null=True)
    patten = models.ForeignKey('Pattern', null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name


class Pattern(models.Model):
    name = models.CharField('الأسم', max_length=255)
    # image = models.ImageField('الصورة', upload_to='media/upload/patterns/', blank=True, null=True)
    typee = models.ForeignKey(PatternType, null=True, on_delete=models.SET_NULL)
    stage = models.ForeignKey(PatternTypeStage, null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['id']

patterns/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def list_pattern_types(request):
    if request.method == 'GET':
        pattern_types = PatternType.objects.all()
        types = PatternType.objects.all()
        stages = PatternTypeStage.objects.all()
        paginator = Paginator(pattern_types, 9)  # Show 4 contacts per page
        page = request.GET.get('page')
        try:
            pattern_types = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            pattern_types = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            pattern_types = paginator.page(paginator.num_pages)
        context = {
            'pattern_types': pattern_types,
            'types': types,
            'stages': stages
        }
        return render(request, 'patternTypes/list_pattern_types.html', context)
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def search(request):
    if request.method == 'GET':
        try:
            typee = request.GET['type']
        except:
            typee = None

        try:
            stage = request.GET['stage']
        except:
            stage = None

        patterns = Pattern.objects.all()
        if typee != '' and typee is not None:
            try:
                typee = PatternType.objects.get(name__icontains=typee)
            except:
                typee = None
            if typee:
                patterns = patterns.filter(typee=typee)

        if stage != '' and stage is not None:
            try:
                stage = PatternTypeStage.objects.get(name=stage)
            except:
                stage = None
            if stage:
                patterns = patterns.filter(stage=stage)
        paginator = Paginator(patterns, 9)  # Show 4 contacts per page
        page = request.GET.get('page')
        try:
            patterns = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            patterns = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            patterns = paginator.page(paginator.num_pages)
        template = 'patterns/searchPatterns.html'
        context = {'patterns': patterns}
        return render(request, template, context)
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def list_pattern_type_stages(request, pk):
    pattern_type_stages = PatternTypeStage.objects.filter(typee__id=pk)

    context = {
        'pattern_type_stages': pattern_type_stages,
    }
    return render(request, 'list_pattern_type_stages.html', context)


def view_pattern(request, pk):
    pattern = Pattern.objects.get(pk=pk)
    return render(request, 'view_pattern.html', {'pattern': pattern})


def view_pattern_type(request, pk):
    try:
        int(pk)
    except:
        return redirect('/')
    pattern_type = PatternType.objects.get(pk=pk)
    pattern_types = PatternType.objects.all()
    # if request.method == 'POST':
    #     if request.POST['type'] != '':
    #         try:
    #             realties = realties.filter(typee__name=request.POST['type'])
    #         except:
    #             realties = Realty.objects.all()
    # paginator = Paginator(patterns, 9)  # Show 4 contacts per page
    # page = request.GET.get('page')
    # try:
    #     patterns = paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer, deliver first page.
    #     patterns = paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range (e.g. 9999), deliver last page of results.
    #     patterns = paginator.page(paginator.num_pages)
    return render(request, 'patternTypes/view_pattern_type.html', {'pattern_type': pattern_type,
                                                                   'pattern_types': pattern_types})

patterns/templates/patternTypes/list_pattern_types.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}
{% load template_blocks %}
{% load slider_extras %}
{% load range %}
{% block content %}
<!-- style -->
<style type="text/css">
    
    #search_submit:hover{
        border:1px solid #fc3e00;
        color:#fc3e00;
        transition-duration:.9s;
    }

</style>
<!-- end style  -->

    <div class="container">
        <div class="col-md-8">
            {% for pattern_type in pattern_types %}
                <a href="/patterns/view_pattern_type/{{ pattern_type.pk }}">
                    <h3 style="text-align:center;">{{ pattern_type.name }}</h3>
                </a>

                <br>

                <div class="panel-group" id="accordion">
                {% for stage in pattern_type.patterntypestage_set.all %}
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{stage.pk}}">
                          {{stage.name}}
                          </a>
                        </h4>
                      </div>
                        {% if forloop.first %}
                            <div id="collapse{{stage.pk}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="row">
                                            {% for pattern in stage.pattern_set.all %}
                                                    <div class="col-md-6">
                                                        {% if pattern.photo.image %}
                                                            <img src="{% resize pattern.photo.id 280 255 %}" 
                                                            style=" border-radius: 10px;padding:4px;">
                                                            <h5 style="text-align:center;">{{pattern.name}}</h5>
                                                        {% else%}
                                                            <img src="/static/imgs/norealimage.jpg">
                                                            <h5 style="text-align:center;">{{pattern.name}}</h5>
                                                        {% endif %}
                                                    </div>
                                            {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div id="collapse{{stage.pk}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="row">
                                        {% for pattern in stage.pattern_set.all %}
                                                <div class="col-md-6">
                                                    {% if pattern.photo.image %}
                                                        <img src="{% resize pattern.photo.id 300 295 %}" 
                                                        style="padding: 4px">
                                                        {{pattern.name}}
                                                    {% else%}
                                                        <img src="/static/imgs/norealimage.jpg">
                                                        {{pattern.name}}
                                                    {% endif %}
                                                </div>
                                        {% endfor %}
                                    </div>
                                </div>
                              </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <hr>
            </div>
        {% endfor %}
        <div class="row">
        <div class="pagenaition">
                    {% if pattern_types.has_previous %}
                        <a href="?page={{ pattern_types.previous_page_number }}" class="start">السابق</a>
                    {% endif %}

                    {% for i in pattern_types.paginator.num_pages|range %}
                        <span>
        {% if pattern_types.number == i %}
            <a href="?page={{ i }}" class="num-page active"
               style="">{{ i }}</a>
        {% else %}
            <a href="?page={{ i }}" class="num-page">{{ i }}</a>
        {% endif %}
      </span>&nbsp;
                    {% endfor %}


                    {% if pattern_types.has_next %}
                        <a href="?page={{ pattern_types.next_page_number }}" class="end">التالي</a>
                    {% endif %}
                    <br>
    <span class="step-links">
        <span class="current" style="float:left; color:white;">
            الصفحة {{ pattern_types.number }} من {{ pattern_types.paginator.num_pages }}
        </span>
        <br>
    </span>
                </div>
                <!-- pajenaition -->
        </div>
        </div> <!-- class col-md-8 -->





        <!-- class col-md-4 -->
        <div class="col-md-4">
        
                <form class="form-search" id="search" method="GET" action="{% url 'search_patterns' %}" style="border-top:2px solid #fc3e00;padding-bottom: 47px !important;">

                        <p><img src="{% static 'imgs/search.png' %}" width="20px"/>بحث في انواع النماذج </p>

                        <div class="row" style="width:96%;">
                            <div class="col-md-3 pull-right">
                                <center style="position: relative; top: 5px;">المرحلة</center>
                            </div>

                            <div class="col-md-9">
                                <input type="text" style="width: 100%;" name="stage" placeholder="أسم المرحلة">
                            </div>
                        </div><!-- row -->

                        <br/>

                        <div class="row" style="width:96%;">

                            <div class="col-md-3 pull-right">  
                                <center style="position: relative; top: 5px;">النوع</center>
                            </div>

                            <div class="col-md-9">
                                <select name="type">
                                    <option value="">نوع النموذج</option>
                                    {% for type in types %}
                                        <option value="{{ type.name }}">{{ type.name }}</option>
                                    {% endfor %}

                                </select>
                            </div> <!-- col-md-9 -->

                        </div><!-- row -->


                        <br/>

                        <button class="btn btn-dafault submit" id="search_submit">ابحث</button>

                </form>

                <br/>
                <div class="advirisment" style="border:1px solid #d4d3d3;">
                    <p class="search-project-title">
                    <span style="background-color:#d03603;">
                       <!--  <img src="{% static 'imgs/tr.jpg' %}"
                             style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
                        <span class="cerve"></span>
                        <img src="{% static 'imgs/magnifying.png' %}" width="18px">
                        <span class="num_visited" style="background-color: #d03603">اعلان</span>
                   </span>
                    </p>


                    <img src="{% static 'imgs/coca.jpg' %}" width="100%" height="400px">

                </div>
        </div> <!-- col-md-4 -->
</div>

{% endblock %}

patterns/templates/patternTypes/view_pattern_type.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}
{% load slider_extras %}
{% block content %}
<style type="text/css">
  div.active{
    background: #fff !important;
  }
  li.active a{
    background: #fff !important;
    border-bottom: 2px solid #FC3E00 !important;
    color: #FC3E00 !important;
  }
</style>

<div class="container" dir="rtl" style="width: 100%; position: relative; right: -2px">
  <div class="row">
    <div class="col-md-8">
      <div class="img-map" style="border: 1px solid silver;
        padding-bottom: 8px;
        margin-bottom: 24px !important;">
                <p class="search-project-title">
                  <span style="background-color:#d03603;">
                 <!--  <img src="{% static 'imgs/tr.jpg' %}" style="position: relative; left: -254px; top: -2.0px; width: 41.0px"> -->
                    <span class="cerve"></span>
                    <img width="18px" src="{% static 'imgs/map.png' %}">
                    <span class="num_visited" style="background-color: #d03603">{{pattern_type.name}}</span>
                  </span>
                </p>
                
        <ul class="list-unstyled list-inline">
          {% for stage in pattern_type.patterntypestage_set.all %}
            {% if forloop.counter == 1 %}
              <li class="active">
                <a data-toggle="tab" href="#tab-pane{{stage.pk}}">{{stage.name}}</a>
              </li>
            {% else %}
              <li>
                <a data-toggle="tab" href="#tab-pane{{stage.pk}}">{{stage.name}}</a>
              </li>
            {% endif %}
          {% endfor %}
        </ul>

        <div class="tab-content">
          {% for stage in pattern_type.patterntypestage_set.all %}
            <div id="tab-pane{{stage.pk}}" class="tab-pane fade in
              {% if forloop.counter == 1 %}active{% endif %}">
               {% for pattern in stage.pattern_set.all %}
                <div class="col-md-6">
                  {% if pattern.photo.image %}
                                <img src="{% resize pattern.photo.id 250 195 %}" 
                                style=" border-radius: 10px;padding:17px;" class="pop imageresource" 
                                data-target="#imagemodal" data-toggle="modal">
                            {% else%}
                                <img src="/static/imgs/norealimage.jpg" width="250" height="230"
                                style=" border-radius: 10px;padding:17px;">
                            {% endif %}
                            <center>
                              <a href="/patterns/view_pattern/{{pattern.pk}}">
                      <h5 style="margin-left:38px;">{{pattern.name}}</h5>
                    </a>
                  </center>
                </div>
               {% endfor %}
            </div>              
          {% endfor %}
        </div>
      </div>
    </div> <!-- col-md-8 -->

    <div class="col-md-4">

      <div class="maps-all" style="border:1px solid #cccccc;">
        <p class="search-project-title">
          <span style="background-color:#d03603;">
         <!--    <img src="{% static 'imgs/tr.jpg' %}" style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
            <span class="cerve"></span>
            <img width="18px" src="{% static 'imgs/map.png' %}">
            <span class="num_visited" style="background-color: #d03603">النماذج</span>
          </span>
        </p>
        <div class="maps-rahab">
          {% for pattern_type in pattern_types %}
            <div style="padding:10px;">
              <a href="/patterns/view_pattern_type/{{pattern_type.pk}}"
              style="color:rgba(0, 0, 0, 0.87); font-size:16px;">
              {{pattern_type.name}}</a>
            </div>
          {% endfor %}
        </div>
      </div><!-- maps-all -->

      <br/>
      <br/>
        <div class="advirisment" style="border:1px solid #d4d3d3;">
            <p class="search-project-title">
            <span style="background-color:#d03603;">
               <!--  <img src="{% static 'imgs/tr.jpg' %}"
                     style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
                <span class="cerve"></span>
                <img src="{% static 'imgs/magnifying.png' %}" width="18px">
                <span class="num_visited" style="background-color: #d03603">اعلان</span>
           </span>
            </p>


            <img src="{% static 'imgs/coca.jpg' %}" width="100%" height="450px">

        </div>
    </div> <!-- col-md-4 -->
  </div><!-- row -->

  <br/>
</div> <!-- end container -->
{% endblock %}