maps/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'all_maps/$', 'maps.views.home', name='index_maps'),
    url(r'show/(?P<pk>\d+)/$', 'maps.views.show', name='show_map'),
    url(r'search/$', 'maps.views.search', name='search_maps'),
    url(r'view_maptype/(?P<pk>\d+)/$', 'maps.views.view_maptype', name="view_maptype"),
]

realestate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'realties.views.home'),
    url(r'^maps/', include('maps.urls')),
    url(r'^realties/', include('realties.urls')),
    url(r'^others/', include('others.urls')),
    url(r'^patterns/', include('patterns.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maps/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.utils import timezone


class MapType(models.Model):
    name = models.CharField('الأسم', max_length=255)
    description = models.TextField('الوصف')

    def __unicode__(self):
        return self.name


class MapTypeStage(models.Model):
    name = models.CharField('الأسم', max_length=255)
    description = models.TextField('الوصف')
    typee = models.ForeignKey(MapType, null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name + ' - ' + self.typee.name



class Map(models.Model):
    name = models.CharField('الأسم', max_length=255)
    # image = models.ImageField('الصورة', upload_to='media/upload/maps/')
    typee = models.ForeignKey(MapType, null=True, on_delete=models.SET_NULL)
    stage = models.ForeignKey(MapTypeStage, null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, null=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, null=True)

    def __unicode__(self):
        return self.name

maps/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def view_maptype(request, pk):
    try:
        maptype = MapType.objects.get(pk=pk)
        allmaptypes = MapType.objects.all()
        context = {
            'maptype': maptype,
            'allmaptypes': allmaptypes
        }
        template = 'view_maptype.html'
        return render(request, template, context)
    except MapType.DoesNotExist:
        return redirect('/')


# Create your views here.
def home(request):
    types = MapType.objects.all()
    paginator = Paginator(types,2)  # Show 4 contacts per page
    page = request.GET.get('page')
    try:
        types = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        types = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        types = paginator.page(paginator.num_pages)
    template = 'index_maps.html'
    context = {
        'types': types
    }
    return render(request, template, context)


def show(request, pk):
    mapp = Map.objects.get(pk=pk)
    context = {
        'map': mapp
    }
    template = 'show_map.html'
    return render(request, template, context)


def search(request):
    if request.method == 'GET':
        try:
            name = request.GET['name']
        except:
            name = None
        try:
            typee = request.GET['type']
        except:
            typee - None
        try:
            stage = request.GET['stage']
        except:
            stage = None
        maps = Map.objects.all()
        if name != '' and name is not None:
            maps = maps.filter(name=name)
        if typee != '' and typee is not None:
            try:
                typee = MapType.objects.get(name=typee)
            except:
                typee = None
            if typee:
                maps = maps.filter(typee=typee)
        if stage != '' and stage is not None:
            try:
                stage = MapTypeStage.objects.get(name=stage)
            except:
                stage = None
            if stage:
                maps = maps.filter(stage=stage)
        context = {
            'maps': maps
        }
        template = 'search_maps.html'
        return render(request, template, context)
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

maps/templates/index_maps.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}
{% load template_blocks %}
{% load slider_extras %}
{% load range %}
{% block content %}
    <div class="container">
    <div class="col-md-8">
        {% for type in types %}
            <a href="/maps/view_maptype/{{ type.id }}" style="text-decoration:none;">
                <h3 style="text-align:center;">{{ type.name }}</h3>
            </a>
            <br>
            <div class="panel-group" id="accordion">
                {% for stage in type.maptypestage_set.all %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion"
                                   href="#collapse{{ stage.pk }}">
                                    {{ stage.name }}</a>
                            </h4>
                        </div>
                        {% if forloop.first %}
                            <div id="collapse{{ stage.pk }}" class="panel-collapse collapse in">
                                <div class="panel-body">
                                    <div class="row">
                                        {% for map in stage.map_set.all %}
                                            <div class="col-md-6">
                                                {% if map.photo.image %}
                                                    <img src="{% resize map.photo.id 300 295 %}"
                                                         style=" border-radius: 10px;padding:4px;">
                                                    <h5 style="text-align:center;">{{ map.name }}</h5>
                                                {% else %}
                                                    <img src="/static/imgs/norealimage.jpg">
                                                    <h5 style="text-align:center;">{{ map.name }}</h5>
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div id="collapse{{ stage.pk }}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="row">
                                        {% for map in stage.map_set.all %}
                                            <div class="col-md-6">
                                                {% if map.photo.image %}
                                                    <img src="{% resize map.photo.id 300 290 %}"
                                                         style="padding: 4px">
                                                    {{ map.name }}
                                                {% else %}
                                                    <img src="/static/imgs/norealimage.jpg">
                                                    {{ map.name }}
                                                {% endif %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                <hr>
            </div>
        {% endfor %}
        <div class="row">
            <div class="pagenaition">
                {% if types.has_previous %}
                    <a href="?page={{ types.previous_page_number }}" class="start">السابق</a>
                {% endif %}

                {% for i in types.paginator.num_pages|range %}
                    <span>
        {% if types.number == i %}
            <a href="?page={{ i }}" class="num-page active"
               style="">{{ i }}</a>
        {% else %}
            <a href="?page={{ i }}" class="num-page">{{ i }}</a>
        {% endif %}
      </span>&nbsp;
                {% endfor %}


                {% if types.has_next %}
                    <a href="?page={{ types.next_page_number }}" class="end">التالي</a>
                {% endif %}
                <br>
    <span class="step-links">
        <span class="current" style="float:left; color:white;">
            الصفحة {{ types.number }} من {{ types.paginator.num_pages }}
        </span>
        <br>
    </span>
            </div>
            <!-- pajenaition -->
        </div>
    </div>
    <div class="col-md-4">
        <br><br>
        <!-- <div class="maps-all" style="border:1px solid #cccccc;">
                <p class="search-project-title">
                    <span style=" background-color:#d03603;">
                        <span class="cerve"></span>
                        <img width="18px" src="{% static 'imgs/visited.png' %}">
                        <span class="num_visited" style="background-color: #d03603">اقسام الموقع</span>
                    </span>
                </p>

                <div class="maps-rahab">
                    <p class="map-title-text" style="padding:10px;line-height: 33px">
                        <img src="{% static 'imgs/932.png' %}" width="5px" style="transform:rotate(180deg)">
                        <a href="*"style="color:#565656;">العقارات</a> <br/>
                        <img src="{% static 'imgs/932.png' %}" width="5px" style="transform:rotate(180deg)"><a href="*"style="color:#565656;">الخرائط</a> <br/>
                        <img src="{% static 'imgs/932.png' %}" width="5px" style="transform:rotate(180deg)"><a href="*"style="color:#565656;">النماذج</a> <br/>
                        <img src="{% static 'imgs/932.png' %}" width="5px" style="transform:rotate(180deg)"><a href="*"style="color:#565656;">اتصل بنا</a> <br/>
                    </p>
                </div>

            </div> -->

        {% view "realties.views.search_view" %}

        <br/>

        <div class="advirisment" style="border:1px solid #d4d3d3;">
            <p class="search-project-title">
                    <span style="background-color:#d03603;">
                       <!--  <img src="{% static 'imgs/tr.jpg' %}"
                             style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
                        <span class="cerve"></span>
                        <img src="{% static 'imgs/magnifying.png' %}" width="18px">
                        <span class="num_visited" style="background-color: #d03603">اعلان</span>
                   </span>
            </p>


            <img src="{% static 'imgs/coca.jpg' %}" width="100%" height="400px">
        </div>
        <!-- col-md-4 -->
    </div>

{% endblock %}

maps/templates/search_maps.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                {% for map in maps %}
                    <div class="col-sm-5" dir="rtl">
                        <p>الخريطه :<a href="{% url 'show_map' map.id %}">{{ map.name }}</a></p>

                        <p> النوع : {{ map.typee.name }}</p>

                        <p> المرحله : {{ map.stage.name }}</p>
                    </div>
                    <div class="col-sm3" dir="rtl">
                        <img src="/media/{{ map.image }}">
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

maps/templates/show_map.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}
{% load template_blocks %}
{% load slider_extras %}
{% block content %}
<div class="container" dir="rtl" style="width: 100%; position: relative; right: -2px">
    <div class="col-md-8">
        <div class="col-md-6">
        	{% if map.photo.image %}
                <img src="{% resize map.photo.id 300 295 %}" 
                style=" border-radius: 10px;padding:4px;" class="img-responsive">
            {% else%}
                <img src="/static/imgs/norealimage.jpg"class="img-responsive">
            {% endif %}
            <br/><br/><br/>
        </div>
        <div class="col-md-6">
            <table class="ui fixed single line celled table buyinvoice">
                    <tbody>
                            <tr>
                                <td style="text-align:center; font-weight:bold; background:#F6F4F2;">
                                أسم الخريطة</td>
                                <td style="text-align:center;">{{ map.name }}</td>
                            </tr>
                            <tr>
                                <td style="text-align:center; font-weight:bold; background:#F6F4F2;">النوع</td>
                                <td style="text-align:center;">
                                    {{ map.stage.typee.name }}
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align:center; font-weight:bold; background:#F6F4F2;">المرحلة</td>
                                <td style="text-align:center;">{{ map.stage.name }}</td>
                            </tr>
                    </tbody>
                </table>
        </div>
        <div class="advertising">
            <img width="93%" height="65%" src="{% static 'imgs/ad1.jpg' %}" style="position: relative; right: 23px">
        </div><!-- advertising -->
    </div>
    <div class="col-md-4">
        
    </div>
</div> <!-- end container -->
{% endblock %}

maps/templates/view_maptype.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}
{% load template_blocks %}
{% load slider_extras %}
{% block content %}
<style type="text/css">
	div.active{
		background: #fff !important;
	}
	li.active a{
		background: #fff !important;
		border-bottom: 2px solid #FC3E00 !important;
		color: #FC3E00 !important;
	}
</style>

<div class="container" dir="rtl" style="width: 100%; position: relative; right: -2px">
	<div class="row">
		<div class="col-md-8">
			<div class="img-map" style="border:1px solid silver;" >
				<p class="search-project-title">
					<span style="background-color:#d03603;">
					<!-- <img src="{% static 'imgs/tr.jpg' %}" style="position: relative; left: -254px; top: -2.0px; width: 41.0px"> -->
						<span class="cerve"></span>
						<img width="18px" src="{% static 'imgs/map.png' %}">
						<span class="num_visited" style="background-color: #d03603">{{maptype.name}}</span>
					</span>
				</p>
				  <ul class="list-unstyled list-inline">
				  	{% for stage in maptype.maptypestage_set.all %}
				  		{% if forloop.counter == 1 %}
				  			<li class="active">
				  				<a data-toggle="tab" href="#tab-pane{{stage.pk}}">{{stage.name}}</a>
				  			</li>
				  		{% else %}
				  			<li>
				  				<a data-toggle="tab" href="#tab-pane{{stage.pk}}">{{stage.name}}</a>
				  			</li>
				  		{% endif %}
				  	{% endfor %}
				  </ul>
				  <div class="tab-content">
				    {% for stage in maptype.maptypestage_set.all %}
			  			<div id="tab-pane{{stage.pk}}" class="tab-pane fade in
			  				{% if forloop.counter == 1 %}active{% endif %}">
			  				 {% for map in stage.map_set.all %}
			  				 	<div class="col-md-4 pull-right">
				  				 	{% if map.photo.image %}
			                            <img src="{% resize map.photo.id 250 195 %}" 
			                            style=" border-radius: 10px;padding:8px;" class="pop imageresource" 
			                            data-target="#imagemodal" data-toggle="modal">
			                        {% else%}
			                            <img src="/static/imgs/norealimage.jpg" width="200" height="205"
			                            style=" border-radius: 10px;padding:8px;">
			                        {% endif %}
			                        <center>
			                        	<a href="/maps/show/{{map.pk}}">
				  				 			<h5 style="margin-left:38px;">{{map.name}}</h5>
				  				 		</a>
				  				 	</center>
			  				 	</div>
			  				 {% endfor %}
					    </div>				  		
				  	{% endfor %}
				</div>
			</div><!-- img-map -->
		</div> <!-- col-md-8 -->

		<div class="col-md-4">

			<div class="maps-all" style="border:1px solid #cccccc;">
				<p class="search-project-title">
					<span style="background-color:#d03603;">
						<!-- <img src="{% static 'imgs/tr.jpg' %}" style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
						<span class="cerve"></span>
						<img width="18px" src="{% static 'imgs/map.png' %}">
						<span class="num_visited" style="background-color: #d03603">الخرائط</span>
					</span>
				</p>
				<div class="maps-rahab">
					{% for maptype in allmaptypes %}
						<div style="padding:10px;">
							<a href="/maps/view_maptype/{{maptype.pk}}"
							style="color:rgba(0, 0, 0, 0.87); font-size:16px;">
							{{maptype.name}}</a>
						</div>
					{% endfor %}
				</div>
			</div><!-- maps-all -->

			<br/>
			<div class="advirisment" style="border:1px solid #d4d3d3;">
			    <p class="search-project-title">
			    <span style="background-color:#d03603;">
			       <!--  <img src="{% static 'imgs/tr.jpg' %}"
			             style="position: relative; left: -182px; top: -2px; width: 40.5px"> -->
			        <span class="cerve"></span>
			        <img src="{% static 'imgs/magnifying.png' %}" width="18px">
			        <span class="num_visited" style="background-color: #d03603">اعلان</span>
			   </span>
			    </p>


			    <img src="{% static 'imgs/adver2.jpg' %}" width="100%" height="450px">

			</div>
		</div> <!-- col-md-4 -->
	</div><!-- row -->

	<br/>

	<!-- image modal -->
	<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">ألغاء</span></button>
	        <h4 class="modal-title" id="myModalLabel">عرض الصورة</h4>
	      </div>
	      <div class="modal-body">
	        <img src="" id="imagepreview" style="width: 100%; height: 100%" >
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">ألغاء</button>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- image modal -->
	
</div> <!-- end container -->
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(".pop").on("click", function() {
           $('#imagepreview').attr('src', $('.imageresource').attr('src')); // here asign the image to the modal when the user click the enlarge link
           $('#imagemodal').modal('show'); // imagemodal is the id attribute assigned to the bootstrap modal, then i use the show function
        });
</script>
{% endblock %}